### ISSUE TITLE
Spaces in <loc> cause cause Malformed sitemap, no urlset

### ISSUE THREAD

**Issue by heaven** [benbalter/sitemap-parser#24]
The error is raised if `sitemapindex` contains an entry where `<loc>` has spaces around the URL.

Example:
```
<sitemap>
  <loc> https://www.showtimes.com/MoviesByPopularZip.xml </loc>
  <lastmod>2022-01-14</lastmod>
</sitemap>
```

Source https://showtimes.com/sitemap.xml

**Comment by benbalter** [comment]
This should be fixed as of https://github.com/benbalter/sitemap-parser/commit/aeab37a83b5802ac798a895fd8dba8a5b1274532.
